// <auto-generated />
using System;
using Anatini.Server.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anatini.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_normalized_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("About")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("about");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<Guid?>("BannerImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("banner_image_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handle");

                    b.Property<Guid?>("IconImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("icon_image_id");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedHandle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_handle");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.Property<int>("Visibility")
                        .HasMaxLength(16)
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email");

                    b.HasIndex("NormalizedHandle")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_handle");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_user_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserChannel", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("UserId", "ChannelId")
                        .HasName("pk_user_channels");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_user_channels_channel_id");

                    b.ToTable("user_channels", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfirmationCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("confirmation_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_emails");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_user_emails_normalized_email");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_user_emails_null_user_id_created_at_utc")
                        .HasFilter("user_id IS NULL");

                    b.ToTable("user_emails", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserHandle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handle");

                    b.Property<string>("NormalizedHandle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_handle");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_handles");

                    b.HasIndex("NormalizedHandle")
                        .IsUnique()
                        .HasDatabaseName("ix_user_handles_normalized_handle");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_handles_user_id");

                    b.ToTable("user_handles", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("alt_text");

                    b.Property<string>("BlobContainerName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("blob_container_name");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blob_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_images");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_images_user_id");

                    b.ToTable("user_images", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_logs");

                    b.HasIndex("DateTimeUtc")
                        .HasDatabaseName("ix_user_logs_date_time_utc");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_user_logs_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logs_user_id");

                    b.ToTable("user_logs", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserTrust", b =>
                {
                    b.Property<Guid>("SourceUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_user_id");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("SourceUserId", "TargetUserId")
                        .HasName("pk_user_trusts");

                    b.HasIndex("TargetUserId", "SourceUserId")
                        .HasDatabaseName("ix_user_trusts_target_user_id_source_user_id");

                    b.ToTable("user_trusts", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("About")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("about");

                    b.Property<Guid?>("BannerImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("banner_image_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DefaultCardImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_card_image_id");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handle");

                    b.Property<Guid?>("IconImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("icon_image_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedHandle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_handle");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Visibility")
                        .HasMaxLength(16)
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_channels");

                    b.HasIndex("NormalizedHandle")
                        .IsUnique()
                        .HasDatabaseName("ix_channels_normalized_handle");

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ChannelHandle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handle");

                    b.Property<string>("NormalizedHandle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_handle");

                    b.HasKey("Id")
                        .HasName("pk_channel_handles");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_channel_handles_channel_id");

                    b.HasIndex("NormalizedHandle")
                        .IsUnique()
                        .HasDatabaseName("ix_channel_handles_normalized_handle");

                    b.ToTable("channel_handles", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ChannelImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("alt_text");

                    b.Property<string>("BlobContainerName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("blob_container_name");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blob_name");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_channel_images");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_channel_images_channel_id");

                    b.ToTable("channel_images", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("DateNZ")
                        .HasColumnType("date")
                        .HasColumnName("date_nz");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handle");

                    b.Property<string>("NormalizedHandle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_handle");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Visibility")
                        .HasMaxLength(16)
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_posts");

                    b.HasIndex("DateNZ")
                        .HasDatabaseName("ix_published_posts_date_nz")
                        .HasFilter("status = 1");

                    b.HasIndex("ChannelId", "DateNZ")
                        .HasDatabaseName("ix_posts_channel_id_date_nz");

                    b.HasIndex("ChannelId", "NormalizedHandle")
                        .IsUnique()
                        .HasDatabaseName("ix_posts_channel_id_normalized_handle");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.PostHandle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handle");

                    b.Property<string>("NormalizedHandle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_handle");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.HasKey("Id")
                        .HasName("pk_post_handles");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_handles_post_id");

                    b.HasIndex("ChannelId", "NormalizedHandle")
                        .IsUnique()
                        .HasDatabaseName("ix_post_handles_channel_id_normalized_handle");

                    b.ToTable("post_handles", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.PostImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("alt_text");

                    b.Property<string>("BlobContainerName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("blob_container_name");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blob_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_post_images");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_images_post_id");

                    b.ToTable("post_images", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationRoleClaim", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationRole", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_asp_net_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserChannel", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.Channel", "Channel")
                        .WithMany("UserChannels")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_channels_channels_channel_id");

                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("UserChannels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_channels_users_user_id");

                    b.Navigation("Channel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserClaim", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserEmail", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Emails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_user_emails_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserHandle", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Handles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_handles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserImage", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Images")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_images_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserLog", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logs_users_user_id");

                    b.OwnsOne("Anatini.Server.Context.Entities.UserEventData", "Data", b1 =>
                        {
                            b1.Property<Guid>("ApplicationUserLogId");

                            b1.Property<string>("IPAddress")
                                .IsRequired();

                            b1.HasKey("ApplicationUserLogId");

                            b1.ToTable("user_logs");

                            b1
                                .ToJson("data")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationUserLogId")
                                .HasConstraintName("fk_user_logs_user_logs_id");
                        });

                    b.Navigation("Data")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserLogin", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserRole", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_asp_net_roles_role_id");

                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserToken", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserTrust", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "SourceUser")
                        .WithMany("GivenTrusts")
                        .HasForeignKey("SourceUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_trusts_users_source_user_id");

                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "TargetUser")
                        .WithMany("ReceivedTrusts")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_trusts_users_target_user_id");

                    b.Navigation("SourceUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ChannelHandle", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.Channel", "Channel")
                        .WithMany("Handles")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_handles_channels_channel_id");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ChannelImage", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.Channel", "Channel")
                        .WithMany("Images")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_images_channels_channel_id");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.Post", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.Channel", "Channel")
                        .WithMany("Posts")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_channels_channel_id");

                    b.OwnsOne("Anatini.Server.Context.Entities.PostOwnedVersion", "DraftVersion", b1 =>
                        {
                            b1.Property<Guid>("PostId");

                            b1.Property<string>("Article")
                                .IsRequired();

                            b1.Property<Guid?>("CardImageId");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.HasKey("PostId")
                                .HasName("pk_posts");

                            b1.ToTable("posts");

                            b1
                                .ToJson("draft_version")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PostId")
                                .HasConstraintName("fk_posts_posts_post_id");
                        });

                    b.OwnsOne("Anatini.Server.Context.Entities.PostOwnedVersion", "PublishedVersion", b1 =>
                        {
                            b1.Property<Guid>("PostId");

                            b1.Property<string>("Article")
                                .IsRequired();

                            b1.Property<Guid?>("CardImageId");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.HasKey("PostId");

                            b1.ToTable("posts");

                            b1
                                .ToJson("published_version")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PostId")
                                .HasConstraintName("fk_posts_posts_id");
                        });

                    b.Navigation("Channel");

                    b.Navigation("DraftVersion")
                        .IsRequired();

                    b.Navigation("PublishedVersion");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.PostHandle", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.Channel", "Channel")
                        .WithMany("PostHandles")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_handles_channels_channel_id");

                    b.HasOne("Anatini.Server.Context.Entities.Post", "Post")
                        .WithMany("Handles")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_handles_posts_post_id");

                    b.Navigation("Channel");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.PostImage", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.Post", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_images_posts_post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationRole", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Emails");

                    b.Navigation("GivenTrusts");

                    b.Navigation("Handles");

                    b.Navigation("Images");

                    b.Navigation("Logins");

                    b.Navigation("Logs");

                    b.Navigation("ReceivedTrusts");

                    b.Navigation("Roles");

                    b.Navigation("Tokens");

                    b.Navigation("UserChannels");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.Channel", b =>
                {
                    b.Navigation("Handles");

                    b.Navigation("Images");

                    b.Navigation("PostHandles");

                    b.Navigation("Posts");

                    b.Navigation("UserChannels");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.Post", b =>
                {
                    b.Navigation("Handles");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
