// <auto-generated />
using System;
using Anatini.Server.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anatini.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name")
                        .HasColumnOrder(1);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_normalized_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type")
                        .HasColumnOrder(2);

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value")
                        .HasColumnOrder(3);

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("About")
                        .HasColumnType("text")
                        .HasColumnName("about")
                        .HasColumnOrder(7);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count")
                        .HasColumnOrder(13);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp")
                        .HasColumnOrder(14);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasColumnOrder(19);

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email")
                        .HasColumnOrder(2);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed")
                        .HasColumnOrder(15);

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handle")
                        .HasColumnOrder(1);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled")
                        .HasColumnOrder(12);

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end")
                        .HasColumnOrder(11);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name")
                        .HasColumnOrder(5);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email")
                        .HasColumnOrder(17);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name")
                        .HasColumnOrder(18);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash")
                        .HasColumnOrder(8);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number")
                        .HasColumnOrder(3);

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed")
                        .HasColumnOrder(16);

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp")
                        .HasColumnOrder(9);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasColumnOrder(20);

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name")
                        .HasColumnOrder(4);

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility")
                        .HasColumnOrder(6);

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Handle")
                        .IsUnique()
                        .HasDatabaseName("ix_users_handle");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_user_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type")
                        .HasColumnOrder(2);

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value")
                        .HasColumnOrder(3);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserContentEdge", b =>
                {
                    b.Property<Guid>("SourceUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_user_id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("TargetContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_content_id")
                        .HasColumnOrder(1);

                    b.Property<int>("Label")
                        .HasColumnType("integer")
                        .HasColumnName("label")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasColumnOrder(3);

                    b.HasKey("SourceUserId", "TargetContentId", "Label")
                        .HasName("pk_user_content_edges");

                    b.HasIndex("TargetContentId", "Label", "SourceUserId")
                        .HasDatabaseName("ix_user_content_edges_target_content_id_label_source_user_id");

                    b.ToTable("user_content_edges", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("ConfirmationCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("confirmation_code")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasColumnOrder(6);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email")
                        .HasColumnOrder(2);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed")
                        .HasColumnOrder(4);

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasColumnOrder(7);

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("pk_user_emails");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_user_emails_normalized_email");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_user_emails_null_user_id_created_at_utc")
                        .HasFilter("user_id IS NULL");

                    b.ToTable("user_emails", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserHandle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasColumnOrder(3);

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handle")
                        .HasColumnOrder(2);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("pk_user_handles");

                    b.HasIndex("Handle")
                        .IsUnique()
                        .HasDatabaseName("ix_user_handles_handle");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_handles_user_id");

                    b.ToTable("user_handles", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserImage", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(0);

                    b.Property<string>("Handle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handle")
                        .HasColumnOrder(1);

                    b.Property<string>("AltText")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("alt_text")
                        .HasColumnOrder(4);

                    b.Property<string>("BlobContainerName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("blob_container_name")
                        .HasColumnOrder(3);

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blob_name")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasColumnOrder(6);

                    b.HasKey("UserId", "Handle")
                        .HasName("pk_user_images");

                    b.ToTable("user_images", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider")
                        .HasColumnOrder(0);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key")
                        .HasColumnOrder(1);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name")
                        .HasColumnOrder(2);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(3);

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasColumnOrder(1);

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserSpaceEdge", b =>
                {
                    b.Property<Guid>("SourceUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_user_id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("TargetSpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_space_id")
                        .HasColumnOrder(1);

                    b.Property<int>("Label")
                        .HasColumnType("integer")
                        .HasColumnName("label")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasColumnOrder(3);

                    b.HasKey("SourceUserId", "TargetSpaceId", "Label")
                        .HasName("pk_user_space_edges");

                    b.HasIndex("TargetSpaceId", "Label", "SourceUserId")
                        .HasDatabaseName("ix_user_space_edges_target_space_id_label_source_user_id");

                    b.ToTable("user_space_edges", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(0);

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasColumnOrder(2);

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value")
                        .HasColumnOrder(3);

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserUserEdge", b =>
                {
                    b.Property<Guid>("SourceUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_user_id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id")
                        .HasColumnOrder(1);

                    b.Property<int>("Label")
                        .HasColumnType("integer")
                        .HasColumnName("label")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasColumnOrder(3);

                    b.HasKey("SourceUserId", "TargetUserId", "Label")
                        .HasName("pk_user_user_edges");

                    b.HasIndex("TargetUserId", "Label", "SourceUserId")
                        .HasDatabaseName("ix_user_user_edges_target_user_id_label_source_user_id");

                    b.ToTable("user_user_edges", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Article")
                        .HasColumnType("text")
                        .HasColumnName("article")
                        .HasColumnOrder(9);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp")
                        .HasColumnOrder(12);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasColumnOrder(13);

                    b.Property<int?>("CurrentVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("current_version_number")
                        .HasColumnOrder(11);

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handle")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name")
                        .HasColumnOrder(8);

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc")
                        .HasColumnOrder(6);

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id")
                        .HasColumnOrder(2);

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasColumnOrder(5);

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasColumnOrder(14);

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url")
                        .HasColumnOrder(10);

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(1);

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility")
                        .HasColumnOrder(7);

                    b.HasKey("Id")
                        .HasName("pk_contents");

                    b.HasIndex("PublishedAtUtc")
                        .HasDatabaseName("ix_published_contents_date_nz")
                        .HasFilter("status = 1");

                    b.HasIndex("SpaceId", "Type", "Handle")
                        .IsUnique()
                        .HasDatabaseName("ix_contents_space_id_type_handle")
                        .HasFilter("space_id IS NOT NULL");

                    b.HasIndex("UserId", "Type", "Handle")
                        .IsUnique()
                        .HasDatabaseName("ix_contents_user_id_type_handle")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("contents", null, t =>
                        {
                            t.HasCheckConstraint("ck_contents_user_id_xor_space_id", "(user_id IS NULL AND space_id IS NOT NULL) OR (space_id IS NULL AND user_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ContentImage", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_id")
                        .HasColumnOrder(0);

                    b.Property<string>("Handle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handle")
                        .HasColumnOrder(1);

                    b.Property<string>("AltText")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("alt_text")
                        .HasColumnOrder(4);

                    b.Property<string>("BlobContainerName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("blob_container_name")
                        .HasColumnOrder(3);

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blob_name")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasColumnOrder(6);

                    b.HasKey("ContentId", "Handle")
                        .HasName("pk_content_images");

                    b.ToTable("content_images", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ContentVersion", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_id")
                        .HasColumnOrder(0);

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number")
                        .HasColumnOrder(1);

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("article")
                        .HasColumnOrder(2);

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasColumnOrder(5);

                    b.HasKey("ContentId", "VersionNumber")
                        .HasName("pk_content_versions");

                    b.ToTable("content_versions", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.EventException", b =>
                {
                    b.Property<Guid>("EventSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_series_id");

                    b.Property<DateTime>("OriginalDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("original_date_utc");

                    b.Property<string>("CustomName")
                        .HasColumnType("text")
                        .HasColumnName("custom_name");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cancelled");

                    b.Property<DateTime?>("RescheduledStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rescheduled_start_utc");

                    b.HasKey("EventSeriesId", "OriginalDateUtc")
                        .HasName("pk_event_exceptions");

                    b.ToTable("event_exceptions", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.EventInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<Guid>("EventSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_series_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_event_instances");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("ix_event_instances_space_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_event_instances_user_id");

                    b.ToTable("event_instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_instances_user_id_xor_space_id", "(user_id IS NULL AND space_id IS NOT NULL) OR (space_id IS NULL AND user_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.EventSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RecurrenceRule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recurrence_rule");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_event_series");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("ix_event_series_space_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_event_series_user_id");

                    b.ToTable("event_series", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_series_user_id_xor_space_id", "(user_id IS NULL AND space_id IS NOT NULL) OR (space_id IS NULL AND user_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasColumnOrder(7);

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type")
                        .HasColumnOrder(3);

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("ip_address")
                        .HasColumnOrder(4);

                    b.Property<string>("MetaData")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_data")
                        .HasColumnOrder(6);

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id")
                        .HasColumnOrder(2);

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("user_agent")
                        .HasColumnOrder(5);

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("pk_logs");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_logs_created_at_utc");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_logs_event_type");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("ix_logs_space_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_logs_user_id");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("About")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("about")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasColumnOrder(5);

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handle")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasColumnOrder(6);

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility")
                        .HasColumnOrder(3);

                    b.HasKey("Id")
                        .HasName("pk_spaces");

                    b.HasIndex("Handle")
                        .IsUnique()
                        .HasDatabaseName("ix_spaces_handle");

                    b.ToTable("spaces", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.SpaceHandle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasColumnOrder(3);

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handle")
                        .HasColumnOrder(2);

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("pk_space_handles");

                    b.HasIndex("Handle")
                        .IsUnique()
                        .HasDatabaseName("ix_space_handles_handle");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("ix_space_handles_space_id");

                    b.ToTable("space_handles", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.SpaceImage", b =>
                {
                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id")
                        .HasColumnOrder(0);

                    b.Property<string>("Handle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handle")
                        .HasColumnOrder(1);

                    b.Property<string>("AltText")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("alt_text")
                        .HasColumnOrder(4);

                    b.Property<string>("BlobContainerName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("blob_container_name")
                        .HasColumnOrder(3);

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blob_name")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasColumnOrder(6);

                    b.HasKey("SpaceId", "Handle")
                        .HasName("pk_space_images");

                    b.ToTable("space_images", (string)null);
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationRoleClaim", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationRole", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_asp_net_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserClaim", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserContentEdge", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "SourceUser")
                        .WithMany("ContentEdges")
                        .HasForeignKey("SourceUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_content_edges_users_source_user_id");

                    b.HasOne("Anatini.Server.Context.Entities.Content", "TargetContent")
                        .WithMany("UserEdges")
                        .HasForeignKey("TargetContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_content_edges_contents_target_content_id");

                    b.Navigation("SourceUser");

                    b.Navigation("TargetContent");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserEmail", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Emails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_user_emails_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserHandle", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Handles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_handles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserImage", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Images")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_images_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserLogin", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserRole", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_asp_net_roles_role_id");

                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserSpaceEdge", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "SourceUser")
                        .WithMany("SpaceEdges")
                        .HasForeignKey("SourceUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_space_edges_users_source_user_id");

                    b.HasOne("Anatini.Server.Context.Entities.Space", "TargetSpace")
                        .WithMany("UserEdges")
                        .HasForeignKey("TargetSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_space_edges_spaces_target_space_id");

                    b.Navigation("SourceUser");

                    b.Navigation("TargetSpace");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserToken", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUserUserEdge", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "SourceUser")
                        .WithMany("GivenUserEdges")
                        .HasForeignKey("SourceUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_user_edges_users_source_user_id");

                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "TargetUser")
                        .WithMany("ReceivedUserEdges")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_user_edges_users_target_user_id");

                    b.Navigation("SourceUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.Content", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.Space", "Space")
                        .WithMany("Contents")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contents_spaces_space_id");

                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Contents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contents_users_user_id");

                    b.Navigation("Space");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ContentImage", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.Content", "Content")
                        .WithMany("Images")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_images_contents_content_id");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ContentVersion", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.Content", "Content")
                        .WithMany("Versions")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_versions_contents_content_id");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.EventInstance", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.Space", "Space")
                        .WithMany("EventInstances")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_event_instances_spaces_space_id");

                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("EventInstances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_event_instances_users_user_id");

                    b.Navigation("Space");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.EventSeries", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.Space", "Space")
                        .WithMany("EventSeries")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_event_series_spaces_space_id");

                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("EventSeries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_event_series_users_user_id");

                    b.Navigation("Space");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.Log", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.Space", "Space")
                        .WithMany("Logs")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_logs_spaces_space_id");

                    b.HasOne("Anatini.Server.Context.Entities.ApplicationUser", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_logs_users_user_id");

                    b.Navigation("Space");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.SpaceHandle", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.Space", "Space")
                        .WithMany("Handles")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_space_handles_spaces_space_id");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.SpaceImage", b =>
                {
                    b.HasOne("Anatini.Server.Context.Entities.Space", "Space")
                        .WithMany("Images")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_space_images_spaces_space_id");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationRole", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("ContentEdges");

                    b.Navigation("Contents");

                    b.Navigation("Emails");

                    b.Navigation("EventInstances");

                    b.Navigation("EventSeries");

                    b.Navigation("GivenUserEdges");

                    b.Navigation("Handles");

                    b.Navigation("Images");

                    b.Navigation("Logins");

                    b.Navigation("Logs");

                    b.Navigation("ReceivedUserEdges");

                    b.Navigation("Roles");

                    b.Navigation("SpaceEdges");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.Content", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("UserEdges");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Anatini.Server.Context.Entities.Space", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("EventInstances");

                    b.Navigation("EventSeries");

                    b.Navigation("Handles");

                    b.Navigation("Images");

                    b.Navigation("Logs");

                    b.Navigation("UserEdges");
                });
#pragma warning restore 612, 618
        }
    }
}
